#!/bin/bash

cd /home/superstar &&
    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo chmod +x code-deploy-scripts/after-install &&
    docker-compose build --no-cache