# Generated by Django 4.2 on 2023-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="media"
            ),
        ),
    ]
