# Generated by Django 4.2 on 2023-05-23 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authent", "0003_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
