Description: >
  Superstar

# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Superstar
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  # InstanceEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     InstanceId: !Ref EC2Instance

  
          sudo service codedeploy-agent startEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: superstar
      ImageId: ami-053b0d53c279acc90
      IamInstanceProfile:
        Arn: arn:aws:iam::703240068765:role/superstarInstanceRole
      Tags:
        - Key: Name
          Value: !Sub Superstar
        - Key: Project
          Value: Backend

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt-get install -y ruby
          cd /home/ubuntu
          wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto > /tmp/logfile
          sudo service codedeploy-agent stop

Outputs:
  ExportedRole:
    Value: !Ref superstarInstanceRole
    Export:
      Name: "superstarInstanceRole"
